debug = true

[registry."docker.io"]
  http = true  
  insecure = true
  mirrors = ["http://docker-neole.io:5000"]

[registry."docker-neole.io:5000"]
  http = true

[worker.oci]
  enabled = true
  gc = true

  [[worker.oci.gcpolicy]]
    filters = ["type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
    keepBytes = 37580963840  # 35 GB, expressed in bytes

  [[worker.oci.gcpolicy]]
    all = true
    keepBytes = 64424509440  # 60 GB, expressed in bytes

[worker.containerd]
  gc = true